all:
	g++ -ggdb -gdwarf-2 MainProgram.cpp Organizer.cpp Instruction.cpp RandomNumberGrabber.cpp FrameTable.cpp ReplaceAlg.cpp FIFOalg.cpp SCalg.cpp VClockAlg.cpp RandomAlg.cpp LRUalg.cpp NRUalg.cpp -o output.out
